name: Artifacts Demo

on:
  push:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Create test reports
      run: |
        mkdir -p reports
        echo "Test results: PASSED" > reports/test-results.txt
        echo "Coverage: 95%" > reports/coverage.txt
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/
        
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: reports/
        
  download-and-verify:
    runs-on: ubuntu-latest
    needs: build-and-upload
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./downloaded-build
        
    - name: Download test reports
      uses: actions/download-artifact@v4
      with:
        name: test-reports
        path: ./downloaded-reports
        
    - name: Verify artifacts
      run: |
        echo "Build files:"
        ls -la ./downloaded-build
        echo "Test reports:"
        cat ./downloaded-reports/*.txt
